name: flutter_local_search_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.5.0  # 웹뷰 기능을 위한 패키지
  dio: ^5.0.0  # 데이터 요청을 위한 패키지
  flutter_riverpod: ^2.0.0  # 상태 관리 패키지
  flutter_html: ^2.2.1  # HTML 콘텐츠를 Flutter 위젯으로 렌더링
  geolocator: ^8.0.0   # 기기 위치 정보 얻기 위한 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 앱에서 사용할 asset이나 폰트가 있으면 여기에 추가
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
